spring:
  ## Mysql Connection
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 3000
      maxLifetime: 1800000
      maximumPoolSize: 50
    jdbc-url: jdbc:mysql://localhost:3306/dcrm?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: javacrm
    password: Javacrm@12345
    driver-class-name: com.mysql.cj.jdbc.Driver